[package]
name = "multid"
version = "0.1.1"
edition = "2024"
readme = "README.md"
keywords = ["arrays"]
repository = "https://github.com/swizzard/multid"
description = "2-d arrays, badly"
license = "MIT"

[dependencies]
thiserror = "2.0.12"
